sudo: required
services: 
  - docker

before_install:
  - docker build -t gra30/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true gra30/react-test npm test

after_success:
  - docker build -t gra30/multi-client ./client
  - docker build -t gra30/multi-nginx ./nginx
  - docker build -t gra30/multi-server ./server
  - docker build -t gra30/multi-worker ./worker
  # Login to the docker CLI
  - echo "$DOCKER_PWD" | docker login -u "$DOCKER_ID" --password-stdin
  # Thake those images and push them to docker hub
  - docker push gra30/multi-client
  - docker push gra30/multi-nginx
  - docker push gra30/multi-server
  - docker push gra30/multi-worker
